APP_ICON = ""
STOP_ICON = "res/Stop32-1.ico"
START_ICON = "res/Start32-3.ico"
GPS_CONFIG_ICON = "res/png-0011.png"
RADAR_CONFIG_ICON = "res/png-0011.png"
SYSTEM_CONFIG_ICON = "res/png-0011.png"
MESWHELL_CONFIG_ICON = "res/png-0011.png"
PATH_CONFIG_ICON = "res/png-0057.png"
PROGRAM_ICON = "res/wave.jpg"

DEFAULT_DATA_NAME = "data/"
DEFAULT_MOCK_GPS = "data/mocks/CAS_S500Y_4.GPR"
DEFAULT_MOCK_RADAR_PRIOR = "data/mocks/CAS_S500Y_4.bin"
DEFAULT_MOCK_RADAR_UNREGISTERED = "data/mocks/CAS_S500Y_5.bin"

DEFAULT_WEIGHT_FILE = "tensorflow/faster-rcnn-keras-master/logs/epoch216-loss0.685-rpn0.265-roi0.420.h5"
DEFAULT_CLASSES_FILE = "tensorflow/faster-rcnn-keras-master/model_data/myclasses.txt"
